name: Discord Notify

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, closed, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"<@909319246759219270> <@396517837209993217> <@924329416623022110> <@475207005926064139> <@1085939891130597396> **[${{ github.repository }}]** ${{ github.actor }}의 ${{ github.event_name }} 이벤트가 발생했어요!\n브랜치: ${{ github.ref_name }}\n커밋: ${{ github.event.head_commit.message }}\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
